### ISSUE TITLE
0F ModCard slot broken for VC-patched games

### ISSUE THREAD

**Issue by M4he** [Prof9/Aio-Kaizou#2]
The `0F` ModCard slot carrying the PET color ModCards does not work on either Blue Moon or Red Sun when the games are patched with their respective Wii U Virtual Console (VC) patch.
The slot entry disappears (set to `---`) when attempted to be activated and becomes unusable. This prevents the PET color ModCards to be used at all in the VC-patched games.

## Steps to reproduce

1. Patch a save file from either a VC-patched Blue Moon or VC-patched Red Sun using the AIO Patcher.
2. Load the save in the game.
3. Open the MegaMan screen and switch to the ModCards overview by pressing the right d-pad twice.
4. Navigate to the `0F` card slot.
5. (optional) select a different PET color with L/R.
6. Press A.

### Expected result

- message "Custom set!" should appear
- the PET screen should change color accordingly
- the `0F` ModCard slot works correctly and can be enabled/disabled at will

### Actual result

- the message "Custom reset!" [sic] appears
- the slot is cleared (set to `---`) instead of activated
- the PET color does not change
- the `0F` ModCard slot becomes unusable

## Notes

- once the `0F` slot is cleared (set to `---`), it cannot be restored until the AIO patcher is used again
- either pressing A or using "Cus ON" will always clear the `0F` slot (setting it to `---`), there's no way to actually use it
- slots other than `0F` seem to work just fine, only `0F` seems to be affected
- it works correctly on non-VC-patched US versions of Blue Moon or Red Sun, the issue seems to be specific to the VC-patched games

Reproduced with VC-patched US game versions on mGBA 0.8.3 as well as a 2DS XL using the VC injector.

**Comment by Prof9** [comment]
From what I recall, the VC versions fake a ModCard being (not) present in address 0F in order to enable the Bass XX fight.

So, there's not much I can do about this, unfortunately. What you could try is entering the title screen code to enable Bass XX, maybe that will stop the game from clearing address 0F. That would only be the case for that play session, though.

Thank you for the detailed bug report, though!
